### ISSUE TITLE
vc-build compress throws NullReferenceException when module has no UI

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-build#70]
vc-build version: 3.8.0

When I run `vc-build compress -configuration Release` for a module that has no web part, the tool crashes at the `WebPackBuild` target:
```
13:17:19 [ERR] Target WebPackBuild failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at VirtoCommerce.Build.Build.<>c.<get_WebPackBuild>b__256_1() in /home/runner/work/vc-build/vc-build/src/VirtoCommerce.Build/Build.cs:line 684
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
```

I believe this is due to the fact that property `WebProject` will be `null` when there are no projects matching the pattern:
```
protected static Project WebProject => Solution?.AllProjects.FirstOrDefault(x => x.Name.EndsWith(DefaultProject) || x.Name.EndsWith("VirtoCommerce.Storefront") || x.Name.EndsWith("VirtoCommerce.Build"));
```
Then this line in `WebPackBuild` definition throws the exception:
```
if (FileSystemTasks.FileExists(WebProject.Directory / "package.json"))
```

This seems to be an issue in other targets that touch `WebProject` and also in version 3.9.0, although some access sites use the null-conditional operator `.?` Generally I think web-related targets should gracefully handle the case of UI-less modules, especially since some of them may be invoked as part of complex targets like `Compress` in my case.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8253 has been created

**Comment by Dan-BV** [comment]
Hi, @j-mok ! 
Can you reproduce the same in the latest version of vc-build?

**Comment by j-mok** [comment]
Yup, it's still there:
```
[WRN] WebPackBuild: No solution files found in the current directory
[ERR] WebPackBuild: Target WebPackBuild failed
​
═══════════════════════════════════════
Target             Status      Duration
───────────────────────────────────────
Clean              Succeeded     < 1sec
Restore            Succeeded       0:01
Compile            Succeeded       0:08
WebPackBuild       Failed        < 1sec   // NullReferenceException: Object reference not set to an instance of an object.
Test               NotRun              
Publish            NotRun              
Compress           NotRun              
───────────────────────────────────────
Total                              0:09
═══════════════════════════════════════
​
Build failed on 2022-12-23 13:58:58. (╯°□°）╯︵ ┻━┻
```
I must add that our solution contains multiple modules, it does not follow the [guidelines](https://docs.virtocommerce.org/developer-guide/create-new-module/). Nonetheless `NullReferenceException` is not acceptable in any case.

**Comment by Dan-BV** [comment]
The issue is registered and we put it in our backlog.
Meanwhile the skip option could be used like in the following example


`vc-build Compress -skip WebPackBuild`

**Comment by Dan-BV** [comment]
Hi, @j-mok.
Please check this functionality in the latest vc-build release version 3.11.0
https://github.com/VirtoCommerce/vc-build/releases/tag/3.11.0

**Comment by j-mok** [comment]
Looks like it does not throw `NullReferenceException` anymore. Thanks.
