### ISSUE TITLE
Achieving pure vc-build compress

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-build#71]
vc-build v. 3.8.0

Is it possible to skip some or all of dependencies of `Compress` (`Clean', 'WebPackBuild`, `Test` etc)? I don't want to rebuild or test (this is already done elsewhere in the CI pipeline), just publish and zip. I can't find any options to do that.

**Comment by krankenbro** [comment]
Yes it is possible: vc-build compress -skip Clean+WebPackBuild+Test
